### ISSUE TITLE
Missing view: View [subscribe.list] not found

### ISSUE THREAD

**Issue by typoworx-de** [NathanGeerinck/laravel-newsletter#21]
How to fix this? I figured out how to create an URL to a Mailing-List myself like this (using Demo-Seed):
http://test.local/subscribe/1

But it throws Error 500 and laravel.log indicates this
```
production.ERROR: View [subscribe.list] not found. {"userId":1,"email":"john.doe@gmail.com","exception":"[object] (InvalidArgumentException(code: 0): View [subscribe.list] not found. at /var/www/projects/laravel/laravel-newsletter/public/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137)
```
Looks like there is a missing view?

It would also be great being able to generate/open the link from withing backend and List-View to the frontend URL (as new tab).

**Comment by NathanGeerinck** [comment]
Did you find a solution for this? Or what is the reason of closing the issue?
