### ISSUE TITLE
Creating a list 500 error

### ISSUE THREAD

**Issue by Cannonb4ll** [NathanGeerinck/laravel-newsletter#5]
When I create a **public** list, and returns me to the show page of that list I get a 500 error:

`Next ErrorException: Route [subscriptions.subscribe] not defined.`

In the show.blade.php I commented this and then it worked:

```
                        @if($list->public == true)
                        <tr>
                            <th>Public link</th>
                            <td><input class="form-control" value="{{ route('subscriptions.subscribe', $list) }}"></td>
                        </tr>
                        @endif
```

**Comment by NathanGeerinck** [comment]
Indeed, that is a feature that isn't available yet. I'll delete it.

Thanks!

**Comment by Cannonb4ll** [comment]
Thanks bae
